version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/drawbridge
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      # Normally, this step would be in a custom primary image;
      # we've added it here for the sake of explanation.
      - run: go get github.com/Masterminds/glide

      # install dependencies
      - run: glide install

      - run:
          name: Run unit tests
          command: |
            set -e
            mkdir -p /coverage
            echo "" > /coverage/coverage.txt

            for d in $(go list ./... | grep -v vendor); do
                go test -race -coverprofile=profile.out -covermode=atomic $d
                if [ -f profile.out ]; then
                    cat profile.out >> /coverage/coverage.txt
                    rm profile.out
                fi
            done

            ls /coverage

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/src/drawbridge/vendor"

      - store_artifacts:
          path: /coverage
          destination: raw-test-output

      - store_test_results:
          path: /coverage